name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Runs every time you 'git push' to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # The Robot starts a clean Linux machine in the cloud
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Downloads your code to the cloud machine

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Uses the Secret you just added
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Uses the Secret you just added

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: amantiwari1901/my-python-app:latest # Your Docker Hub Image name